### ISSUE TITLE
Mobile Navbar

### ISSUE THREAD

**Issue by yakeshiaj** [ictn6815project/asteroid-game#1]
**Describe the bug**
The toggle navbar isnt available on the Asteroids and Control pages. 

**To Reproduce**
1. Go to the site on mobile device
2. See error

**Expected behavior**
Expected to see the toggle navbar.

**Screenshots**
<img src="https://user-images.githubusercontent.com/11937413/204833428-4303a2ea-0f6d-4a44-87bc-187813301426.PNG" width="30%" height="auto">
<img src="https://user-images.githubusercontent.com/11937413/204833455-cec1afdf-2ec6-479f-9473-62c6bed3498c.PNG" width="30%" height="auto">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser Google Chrome
 - Version 107.0.5304.110

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: iOS 16
 - Browser: Google Chrome
 - Version 108.0.5359.52

**Additional context**
No further content.

**Comment by ictn6815project** [comment]
has been fixed.
